export const PLACE_CELL_CHANGE = 'PLACE_CELL_CHANGE';
export const PLACE_CELL_CHANGE_SUCCEEDED = 'PLACE_CELL_CHANGE_SUCCEEDED';
export const PLACE_CELL_CHANGE_FAILED = 'PLACE_CELL_CHANGE_FAILED';

export const START_NEW_GAME = 'START_NEW_GAME';
